export const techIconMap: Record<string, string> = {
	Nextjs: "nextjs",
	Vitejs: "vitejs",
	TailwindCss: "tailwindcss",
	Nodejs: "nodejs",
	React: "react",
	Python: "python",
	Typescript: "typescript",
	Javascript: "javascript",
	Django: "django",
	Fastapi: "fastapi",
	ReactRouter: "react",
	Html: "html5",
	Css: "css3",
	Sass: "sass",
	Bootstrap: "bootstrap",
	Redux: "redux",
	Vue: "vuejs",
	Angular: "angularjs",
	Php: "php",
	Laravel: "laravel",
	Mysql: "mysql",
	Postgresql: "postgresql",
	Mongodb: "mongodb",
	Git: "git",
	Github: "github",
	Docker: "docker",
	Aws: "amazonwebservices",
	Linux: "linux",
	Java: "java",
	Csharp: "csharp",
	Cpp: "cplusplus",
	Ruby: "ruby",
	Firebase: "firebase",
	Jest: "jest",
	Nginx: "nginx",
	Kubernetes: "kubernetes"
};

export const techDisplayNameMap: Record<string, string> = {
	Nextjs: "Next.js",
	TailwindCss: "Tailwind CSS",
	Nodejs: "Node.js",
	React: "React",
	Python: "Python",
	Typescript: "TypeScript",
	Javascript: "JavaScript",
	Django: "Django",
	Fastapi: "FastAPI",
	ReactRouter: "React Router",
	Html: "HTML5",
	Css: "CSS3",
	Sass: "Sass",
	Bootstrap: "Bootstrap",
	Redux: "Redux",
	Vue: "Vue.js",
	Angular: "AngularJS",
	Php: "PHP",
	Laravel: "Laravel",
	Mysql: "MySQL",
	Postgresql: "PostgreSQL",
	Mongodb: "MongoDB",
	Git: "Git",
	Github: "GitHub",
	Docker: "Docker",
	Aws: "AWS",
	Linux: "Linux",
	Java: "Java",
	Csharp: "C#",
	Cpp: "C++",
	Ruby: "Ruby",
	Firebase: "Firebase",
	Jest: "Jest",
	Nginx: "Nginx",
	Kubernetes: "Kubernetes",
};
